name: Python application
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:

    - name: Show Current Dir
      run: |
        cd

    - name: Find Requirements.txt
      run: |
        find . -regex '.*requirements.txt$'
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: run the app
      run: |
        python app.py

 