name: Python application
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:

    # - name: Show Current Dir
    #   run: |
    #     cd

    # - name: See Folder Structure
    #   run: |
    #     tree
        
    - name: Install Dependencies
      run: |
        pip install -r .github/workflow/requirements.txt

    - name: run the app
      run: |
        python app.py

 