name: Python application
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:

    # - name: Show Current Dir
    #   run: |
    #     cd

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create a requirements file
      run: |
        pip freeze > requirements.txt
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # - name: Run Tests
    #   run: |
    #     python -m pytest -v

    - name: run the app
      run: |
        python app.py

 